# In this workflow excerpt, the type-check and unit-test jobs run in parallel whereas the
# build job "needs" these 2 jobs to be successful to be kicked off.
# Thus, if any of type-check or unit-test were to fail, the build job will not start and the
# whole workflow will be marked as "failed".

jobs:
  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [12]
    steps:
      - name: Checkout Commit
      uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
      - name: Check types
      run: |
        yarn type-check
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [12]
    steps:
      - name: Checkout Commit
      uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
      - name: Run test
      run: |
        yarn test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [12]
    needs: [type-check, unit-test]
    steps:
      - name: Checkout Commit
      uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
      - name: Run build
      run: |
        yarn build
